version: '3'
services:
  eureka-server:
    build:
      context: ./eureka
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  student:
    build:
      context: ./student/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  library:
    build:
      context: ./library/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"

  order:
    build:
      context: ./order/
      dockerfile: Dockerfile
    ports:
      - "8002:8002"