version: '3'
services:
  database:
    image: mysql
    container_name: mysql-db
    ports:
      - "3307:3306"
    volumes:
    - mysql_volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mynetwork

  student:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: student-service
    ports:
      - "8000:8000"
    environment:
      MYSQL_URL: jdbc:mysql://database:3306/library?autoReconnect=true&createDatabaseIfNotExist=true
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
#      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://192.168.32.2:8761/eureka
      EUREKA_CLIENT_SERVICE-URL_DEFAULTZONE: http://localhost:8761/eureka/
    depends_on:
      - database
    networks:
      - mynetwork

volumes:
  mysql_volume :
networks:
  mynetwork :