version: '3'
services:
  database:
    image: mysql:latest
    container_name: database.dev
    command: mysqld --user=root --verbose
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "library"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DRIVER: "com.mysql.cj.jdbc.Driver"
      MYSQL.HIBERNATE.DIALECT: "org.hibernate.dialect.MySQL5Dialect"
      MYSQL.HIBERNATE.SHOW_SQL: "true"
      MYSQL.HIBERNATE.HBM2DDL.AUTO: "update"


  student:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://library-db:3306/library?autoReconnect=true&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      eureka.client.service-url.defaulZone: http://localhost:8761/eureka
    depends_on:
      - database